[phases]
setup = { nodejs = "20.9.0" }

[phases.install]
commands = [
  "npm install --legacy-peer-deps"
]

[phases.build]
commands = [
  "npm run build"
]

[phases.start]
commands = [
  "npm run start"
]
